### ISSUE TITLE
Do not calculate digests for local archives if they are already set

### ISSUE THREAD

**Issue by bastianeicher** [0install/0repo#12]
Currently 0repo calculates digests for local archives even if `<manifest-digest>` is already set in the feed. This seems to be unnecessarily repeating work done by e.g. 0template. Perhaps the logic could be modified to only calculate missing digests.

**Comment by talex5** [comment]
The idea is that 0repo is run by the repository owner, while 0template is run by the contributor, so it probably makes sense to have it double check, in case the contributor made a mistake.

**Comment by bastianeicher** [comment]
That makes sense. It does make the behavior for local and remote archives somewhat asymmetrical though. The digests provided for both by contributors may be incorrect but only local archives are checked (presumably because they are cheaper).

Would you be open for a patch that makes this behavior configurable via 0repo-config.py?

**Comment by talex5** [comment]
Thanks!
