### ISSUE TITLE
Multiple GPG keys match

### ISSUE THREAD

**Issue by liminalitythree** [0install/0repo#33]
Whenever I try to use ` 0repo create ... ` it gives me the error "multiple keys match keyname"
Even if I generate a fresh key using the instructions in the README

```
$ gpg --gen-key
    realname: dummykey
    email: dummy@example.com
```

Then try to create a repo

```
$ 0repo create myrepo dummykey
Multiple GPG keys match 'dummykey':
sec:u:2048:1:DCAF9F964B7C954A:1509036412:1572108412::u:::scESC::::::23::0:
fpr:::::::::065FBDFD020743453FFDCE15DCAF9F964B7C954A:
grp:::::::::05B4B26D8ABE567716A2D544291B27F217BC4450:
uid:u::::1509036412::EFC484DFD0DF86D40711003FC3155D382E4FEF19::dummykey <dummy@example.com>::::::::::0:
ssb:u:2048:1:645467199279B252:1509036412:1572108412:::::e::::::23:
fpr:::::::::DD2180683DF129456BE0E95A645467199279B252:
grp:::::::::D2A00BA1310DC0201F0C9F2B016C867F0CA9F6FF:
```

I'm not sure how to fix this. The only thing I could think of is that it's because of subkeys, but I don't know how to tell it to use a subkey or something. Can anyone offer any help?

**Comment by talex5** [comment]
What does `gpg --fingerprint dummykey` show?

If there are multiple keys, try using the key fingerprint instead of the short name.

**Comment by liminalitythree** [comment]
gpg --fingerprint dummykey shows 
```
pub   rsa2048 2017-10-26 [SC] [expires: 2019-10-26]
      065F BDFD 0207 4345 3FFD  CE15 DCAF 9F96 4B7C 954A
uid           [ultimate] dummykey <dummy@example.com>
sub   rsa2048 2017-10-26 [E] [expires: 2019-10-26]
```
I think gpg might create a subkey for signing and a subkey for encrypting.
If by key fingerprint you mean '065FBDFD020743453FFDCE15DCAF9F964B7C954A' or 'DD2180683DF129456BE0E95A645467199279B252', both of those fail as well.

```
λ 0repo create test DD2180683DF129456BE0E95A645467199279B252
Multiple GPG keys match 'DD2180683DF129456BE0E95A645467199279B252':
sec:u:2048:1:DCAF9F964B7C954A:1509036412:1572108412::u:::scESC::::::23::0:
fpr:::::::::065FBDFD020743453FFDCE15DCAF9F964B7C954A:
grp:::::::::05B4B26D8ABE567716A2D544291B27F217BC4450:
uid:u::::1509036412::EFC484DFD0DF86D40711003FC3155D382E4FEF19::dummykey <dummy@example.com>::::::::::0:
ssb:u:2048:1:645467199279B252:1509036412:1572108412:::::e::::::23:
fpr:::::::::DD2180683DF129456BE0E95A645467199279B252:
grp:::::::::D2A00BA1310DC0201F0C9F2B016C867F0CA9F6FF:
```

**Comment by liminalitythree** [comment]
I think I fixed it.

I opened the gnome key manager and saw that there were two keys or subkeys for the key
![key-manager](https://i.imgur.com/59Iqs7D.png)

I deleted the key for encryption as I think with 0install you just need to sign.
![key-manager-2](https://i.imgur.com/gi8XJVF.png)

after that ` 0repo create ` worked fine.
