### ISSUE TITLE
Merging of <environment> elements leads to duplicates

### ISSUE THREAD

**Issue by benjamin-hg** [0install/0repo#34]
When a feed is merged and there are `<environment>` tags in the new implementation, these tags are then pulled out to a group (same as with `<requires>` elements). While the extracted `<requires>` elements are removed from their original parent element (the  `<implementation>` ), the  `<environment>` elements remain as duplicates inside the the  `<implementation>` .

**Comment by bastianeicher** [comment]
See of #36 for sample.
